// -------------------------------------------------------------------------------
// GRUNTFILE
// Loading and registering grunt tasks. Shared Grunt config file variables.
// http://gruntjs.com
// -------------------------------------------------------------------------------

module.exports = function(grunt) {
	'use strict';



	// -------------------------------------------------
	// CONFIG
	// -------------------------------------------------

	// Initialize config.
	grunt.initConfig({
		pkg: require('./package.json'),
	});

	// Load tasks automatically with 'load-grunt-tasks' plugin.
	require('load-grunt-tasks')(grunt);



	// -------------------------------------------------
	// SHARED VARIABLES
	// -------------------------------------------------

	var gruntScope = {

		// COMMENT BANNER
		// Placed on generated files to warn developers not to edit dist files directly.
		commentBanner: '/*\nWARNING: Do not edit this file! It is generated automatically from multiple source files.\nLAST MODIFIED: <%= grunt.template.today("yyyy-mm-dd h:MM:ss TT") %>\n*/\n',

		// PATHS
		gruntConfigsPath: 'grunt-configs',
		srcPath: 'src/',
		distPath: 'dist/',
		srcComponentsPath: '<%= srcPath %>components/',

		// HTML FILES
		srcHtmlFiles: ['<%= srcPath %>*.html', '<%= srcComponentsPath %>**/*.html'],
		distHtmlFiles: ['<%= distPath %>*.html'],

		// SASS/CSS FILES
		srcSassFiles: ['<%= srcPath %>*.scss', '<%= srcComponentsPath %>**/*.scss'],
		srcMainSassFile: '<%= srcPath %>main.scss',
		distMainCssFile: '<%= distPath %>all.min.css',

		// JS FILES
		srcJsFiles: ['<%= srcPath %>*.html', '<%= srcComponentsPath %>**/*.html'],
		distMainJsFile: '<%= distPath %>all.min.js',
		gruntConfigFiles: ['Gruntfile.js', '<%= gruntConfigsPath %>*.js'],
	};



	// -------------------------------------------------
	// TASK CONFIGS
	// Load per-task configs from seperate files.
	// -------------------------------------------------

	grunt.loadTasks('<%= gruntScope.gruntConfigsPath %>');



	// -------------------------------------------------
	// REGISTER TASKS
	// -------------------------------------------------

	// DEFAULT
	// Build, start server, live reload, and watch.
	// 'grunt'
	grunt.registerTask('default', ['browsersync', 'watch']);

	// DEBUG
	// Same as default task, except code has been prettified for debugging.
	// 'grunt debug'
	grunt.registerTask('debug', ['sass:debug', 'uglify:debug']);
};
